###############################################################################
# Cognitive Mesh â€” Base Kustomization
###############################################################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cognitive-mesh-base

commonLabels:
  app.kubernetes.io/name: cognitive-mesh
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
